name: Actions

on: 
  pull_request:
    branches:
      - master
      - develop
jobs:
    build:
        name: Run build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn 

            - name: Static build 
              run: yarn build
    lint:
        name: Run lints
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn

            - name: Run Prettier
              run: yarn lint
