name: Actions

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  build-export:
    name: Run Nextjs build and export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.16"
      - run: npm ci 
      - run: npm install
      - run: npm run build 
      - run: npm run export
~                                                                                         
